Name: Charts
Type: FolderType
Children:
- Name: ChartServerType
  Id: g=eacfacaa466e09f902cb5f6522ea6cda
  Supertype: BaseObjectType
  Children:
  - Name: Port
    Type: BaseDataVariableType
    DataType: UInt16
    Value: 49001
  - Name: Charts
    Type: BaseObjectType
  - Name: RootPath
    Type: BaseDataVariableType
    DataType: String
  - Name: Test
    Type: BaseDataVariableType
    DataType: Boolean
  - Class: Method
    Name: Test
    Id: g=ac7824365c2432cc09b319c9cb9e9cac
  - Class: Method
    Name: Test
    Id: g=f16dfc8e98f565090d38424168847184
  - Class: Method
    Name: Test
    Id: g=cddfa63c8781d649528c8346b40a055f
  - Class: Method
    Name: Test
    Id: g=9714580c1914d1e9b4c9990bda7c5c35
  - Class: Method
    Name: Test
    Id: g=8a485803eea56e1263c0a547525066ee
  - Class: Method
    Name: Test
    Id: g=04f63f001757fc62019ca14c00e696a4
  - Class: Method
    Name: Test
    Id: g=79adce90ca82d9431079075309a95b46
  - Class: Method
    Name: Test
    Id: g=aeadd59845a72db088a42e854dd001a4
  - Class: Method
    Name: Test
    Id: g=11bebeaeac14c5f72563a889e3673fdc
  - Class: Method
    Name: Test
    Id: g=a9c94dc4b8b38614e9c63d4c7a7bb4cb
  - Class: Method
    Name: Test
    Id: g=44112cc3f3425bf381663a0cd127ac6d
  - Class: Method
    Name: Test
    Id: g=85da031308383306e1fa58ac04c81ebe
  - Class: Method
    Name: Test
    Id: g=2ccfc2513ad0d13e2e4294ede63f830d
  - Class: Method
    Name: Test
    Id: g=2920d9ce61c66b28a5a7a0b769272ffb
  - Class: Method
    Name: Test
    Id: g=bea90374917991e3992980eb9d65ba37
  - Class: Method
    Name: Test
    Id: g=aa3e0a47f9b29b0488cc0ce39ca201e9
  - Class: Method
    Name: Test
    Id: g=7e7be2fa174a5f0cb192c74316179b3f
  - Class: Method
    Name: Test
    Id: g=5b5df7c569d8b87289454041a78311e1
  - Class: Method
    Name: Test
    Id: g=81924674843025bd3b5cecae8e80f0ea
  - Class: Method
    Name: Test
    Id: g=ced79b7c8cf8836b1a9b58ed3ecbf97b
  - Class: Method
    Name: Test
    Id: g=1e12b115ae96fa0592e688553c272a87
  - Class: Method
    Name: Test
    Id: g=16d797b5b628a262cf9028474f845fe7
  - Class: Method
    Name: Test
    Id: g=e92aae45e10a1cc905c964272ceeda45
  - Class: Method
    Name: Test
    Id: g=12f839a9c260a03cfc38e73e77fb7ff6
  - Class: Method
    Name: Test
    Id: g=43b90ae849e49668b83c1ad8ded7680f
  - Class: Method
    Name: Test
    Id: g=adbd8b00e00428affbf97cd1625ed531
  - Class: Method
    Name: Test
    Id: g=837946c815eed07f83fc5e0c6590827f
  - Class: Method
    Name: Test
    Id: g=7784feed1489ec9ff3dcdfe958aa10f3
  - Class: Method
    Name: Test
    Id: g=1193c8dc91409ee388c0dcc6305c13a9
  - Class: Method
    Name: Test
    Id: g=e353116e350a71fcb641958d3063273c
  - Class: Method
    Name: Test
    Id: g=b3593bafdb2cdd657ad3bfbaedb49116
  - Class: Method
    Name: Test
    Id: g=fbc14169df55e712393ce1edbcec6dc6
  - Class: Method
    Name: Test
    Id: g=1f71ac08e010c82b1e924b05a8713704
  - Class: Method
    Name: Test
    Id: g=6822c5ba6a04d69b50bfcc2dedd78639
  - Class: Method
    Name: Test
    Id: g=405e793954d9b045857336512c08a053
  - Class: Method
    Name: Test
    Id: g=3008ccf0edd118809f9205827f2d1d81
  - Class: Method
    Name: Test
    Id: g=1e80a9c607067ab7c6376adc418f3bb9
  - Class: Method
    Name: Test
    Id: g=7c24a1872ce21fc455a8dbbe26d58fcb
  - Class: Method
    Name: Test
    Id: g=fadaa8221ef9b60a35892e809ed03bfe
  - Class: Method
    Name: Test
    Id: g=c0cff80753160d264ebb55b2860a143b
  - Class: Method
    Name: Test
    Id: g=11e65d0a75b34073f34e7eb68e193bda
  - Class: Method
    Name: Test
    Id: g=78c06d64055083f24db7a05c8c3f679a
  - Class: Method
    Name: Test
    Id: g=6c03d4f94ecfe1e2db156f17db98cd5e
  - Class: Method
    Name: Test
    Id: g=29fb390172cf62c2d4bc37d037ad149c
  - Class: Method
    Name: Test
    Id: g=db93c4b8e9b4dccba22e656066b07514
  - Class: Method
    Name: Test
    Id: g=5cac93d37b5ac480b13300b526a29c62
  - Class: Method
    Name: Test
    Id: g=46d5372d0d6bc6a4f35e71939b83e3a5
  - Class: Method
    Name: Test
    Id: g=09317f36f9d41e85919fe067de1fc598
  - Class: Method
    Name: Test
    Id: g=cfe31e2a739beb9222eac8d5744d8640
  - Class: Method
    Name: Test
    Id: g=00c2d0233f7f7ccf70d3faa2d15178f6
  - Class: Method
    Name: Test
    Id: g=f741eeb13eb2e7c7fc469c082d0ab0fd
  - Class: Method
    Name: Test
    Id: g=868a5c63bb6331ca53a1b9f789c001c0
  - Name: Enable
    Type: BaseDataVariableType
    DataType: Boolean
    Value: true
  - Class: Method
    Name: Test
    Id: g=8b502d38021b3346e54abbda0d46be2c
  - Class: Method
    Name: Test
    Id: g=24b4c22685e2ad5f6c83aa373988f7bf
  - Class: Method
    Name: Test
    Id: g=98e81e30511b8abc95b349b6485dedf1
  - Class: Method
    Name: Test
    Id: g=de4b7f73aec3d3e7f9705ed88f5c7786
  - Class: Method
    Name: Test
    Id: g=e61f0811dc7f21488a709963bd4340e6
  - Name: Error
    Type: BaseDataVariableType
    DataType: String
  - Class: Method
    Name: Test
    Id: g=586c96220747e5222af4f22d86323f11
  - Class: Method
    Name: Test
    Id: g=2ea64a5f71c0f752c77d6524dfff907c
  - Class: Method
    Name: Test
    Id: g=8450f7c67a6a213ae29f967a293c60f6
  - Class: Method
    Name: Test
    Id: g=fe8dbbd8ba3f4e6b9683576f9ffd7131
  - Class: Method
    Name: Test
    Id: g=51c9cc74e3bec9f02d3348217dc0852b
  - Class: Method
    Name: Test
    Id: g=ff324098ba7fb56f26d835459a90d710
  - Class: Method
    Name: Test
    Id: g=852f50435c455cc93715758f56357588
  - Class: Method
    Name: Test
    Id: g=a9ca1a40203417d27fa525c77db194c0
  - Class: Method
    Name: Test
    Id: g=9df83a3a7c7b64676beca0a55989c56a
  - Class: Method
    Name: Test
    Id: g=712e187a7563a076d0e9d253280c55d3
  - Class: Method
    Name: Test
    Id: g=7e56af3829076eb6af7c7cf7f840900e
  - Class: Method
    Name: Test
    Id: g=97b63c3d23671ecf7f351e970a7a7a2f
  - Class: Method
    Name: Test
    Id: g=033bc1fe66f58ac18152ca222f860403
  - Class: Method
    Name: Test
    Id: g=ff47f4ca0a91996dc990f74b089f866f
  - Class: Method
    Name: Test
    Id: g=84818f65200a7cea2267238f71bd44d9
  - Class: Method
    Name: Test
    Id: g=1c47dd3da15a341edb79ae5aa285b63a
  - Class: Method
    Name: Test
    Id: g=6c3275c4d08f3d2514cd175fe9ee50a4
  - Class: Method
    Name: Test
    Id: g=cd4c991f574a798af3cf158579d54d09
  - Class: Method
    Name: Test
    Id: g=177ceecb0f47737e0050090a5164b7d3
  - Class: Method
    Name: Test
    Id: g=5dc977584dd25edaa06fb4a550e11399
  - Class: Method
    Name: Test
    Id: g=6e215f69d6acbac54e7b59fff17aa692
  - Class: Method
    Name: Test
    Id: g=e166e6c8c020d215739de78c14ea1712
  - Class: Method
    Name: Test
    Id: g=d29fed40d277cb426cf9d2a051ebecc4
  - Class: Method
    Name: Test
    Id: g=0d51ffa0e28351f141d4ebfe06f2d6f9
  - Class: Method
    Name: Test
    Id: g=050044b5c44e662ee071720e5d06ba60
  - Class: Method
    Name: Test
    Id: g=612780aaa259f7fb9acad3015cbed0bc
  - Class: Method
    Name: Test
    Id: g=fb26eb364078cff14cdb1d2ca581a868
  - Class: Method
    Name: Test
    Id: g=1f46f7b7750e66f312898ad2f2262036
  - Class: Method
    Name: Test
    Id: g=68f569f46a70d81246bda2b5777feb2b
  - Class: Method
    Name: Test
    Id: g=8d389b78dd9436a22619dcbffa2a8914
- Name: ChartConfigureType
  Id: g=6e42f26de01b31cb7c0c9abea432bb28
  Supertype: BaseObjectType
  Children:
  - Name: Option
    Type: BaseDataVariableType
    DataType: String
  - Name: IsActive
    Type: BaseDataVariableType
    DataType: Boolean
    Description: {"LocaleId":"en-US","Text":"主动生成模式，由后台刷新数据，提供统一数据"}
  - Name: Data
    Type: BaseDataVariableType
    DataType: String
  - Name: GetDataMethod
    Type: BaseDataVariableType
    DataType: String
    Value: "GetData"
  - Name: Period
    Type: BaseDataVariableType
    DataType: Int32
    Value: 5000
  - Name: ScriptPath
    Type: BaseDataVariableType
    DataType: ResourceUri
  - Name: ScriptEnable
    Type: BaseDataVariableType
    DataType: Boolean
  - Name: ActualScriptPath
    Type: BaseDataVariableType
    DataType: String
  - Name: ActualScript
    Type: BaseDataVariableType
    DataType: String
  - Name: SaveTrigger
    Type: BaseDataVariableType
    DataType: Boolean
- Name: WebChartHandle
  Type: NetLogic
